
CC=nvc++ 
LD=nvc++

INCLUDE_DIR=../include/
CFLAGS = -O2  -g  -I${INCLUDE_DIR}  -fopenmp

.PHONY: clean build 

build: stg_cpu.x 

stg_cpu.x: stg_interface.o stg_inputs.o sem.o stg.o
	${LD} ${CFLAGS} $^  -o $@ 

%.o: %.cpp 
	$(CC) -c $(CFLAGS) $<
	
clean:
	rm -rf *.o 

	
